---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: friendbot
  labels:
    app: friendbot
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: friendbot
  template:
    metadata:
      labels:
        app: friendbot
    spec:
      containers:
        - name: friendbot
          image: "{{ .Values.image.repo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - name: friendbot-port
              containerPort: 6000
          env:
            - name: FRIENDBOT_REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: FRIENDBOT_REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: FRIENDBOT_LOG_LEVEL
              value: "{{ .Values.logLevel }}"
            - name: FRIENDBOT_EXPORT_ZIP
              value: /friendbot/export.zip
              # TODO Update to use new secret file
              # Secret will need to be mounted as volume
            - name: FRIENDBOT_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: friendbot-signing-secret
                  key: signingSecret
                  optional: true
          volumeMounts:
            - mountPath: /friendbot
              name: friendbot-export-volume
          livenessProbe:
            httpGet:
              path: /health
              port: friendbot-port
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: friendbot-port
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: friendbot-export-volume
          nfs:
            server: soteria.lan
            path: /volume1/Nolan/friendbot
