---
version: "3.7"
services:
  app:
    image: ghcr.io/barrelmaker97/friendbot:latest
    container_name: friendbot
    ports:
      - "8000:8000"
# Uncomment and change these to configure Friendbot
#   environment:
#     FRIENDBOT_EXPORT_ZIP: /different/location/export.zip
#     FRIENDBOT_LOG_LEVEL: info
#     FRIENDBOT_REDIS_HOST: redis
#     FRIENDBOT_REDIS_PORT: 6379
#     FRIENDBOT_SECRET_FILE: /my/secret/file
    volumes:
      - type: bind
        source: ${FB_EXPORT}
        target: /home/friendbot/export.zip
        read_only: true
    restart: always
# Uncomment this section to cache Friendbot using Redis
# redis:
#   image: "redis:alpine"
#   container_name: redis
#   restart: always
